version: "3.7"
services:
  entropy-db:
    image: postgres:12
    ports:
      - 55432:5432
    volumes:
      #      CREATE DATABASE
      - ./docker/postgres/initdb.sql:/docker-entrypoint-initdb.d/init.sql
      #      PERSIST DATA
      - ./docker/volumes/postgres/pg-data:/var/lib/postgresql/data:z
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  smtp:
    image: mailhog/mailhog
    container_name: mail_service
    ports:
      - 2025:1025
      - 7025:8025
  keycloak:
    build:
      context: ./
      dockerfile: docker/keycloak/Dockerfile
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: entropy-db
      DB_HOST: localhost
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 3entropy
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8500:8080
    depends_on:
      - entropy-db